name = "estateman_cfw"
main="src/index.ts"
#main = "dist/index.mjs"
# workers_dev = true
compatibility_date = "2022-02-03"
# kv_namespaces = [
# ]

[env.staging]
workers_dev = true

[env.staging.vars]
IS_DEBUG = 1 # To Encrypt Password
USER_ENCRYPTION_KEY = "<512-bits encryption key>"
TENANT_ENCRYPTION_KEY = "<512-bits encryption key>"
API_SECRET = "<256-bits encryption key>"
DBINIT_SECRET = "<256-bits encryption key>"
SYSTEM_HOST = "http://localhost:3000" # CFW local server default port. (May change in future)
SYSTEM_EMAIL_SENDER = "<YOUR_EMAIL_SENDER_NAME_WITH_EMAIL>" # e.g. EstateMan <no_reply@propmanagement.com>
NOTIFICATION_ICON_URL = "https://f004.backblazeb2.com/file/vpms-hk/assets/logo3_b_120.png"
# Obtain in Firebase console->project settings->project ID
FIREBASE_PROJECT_ID = "<YOUR_FIREBASE_PROJECT_ID>"
# Obtain in Firebase console->project settings->cloud messaging->legacy API
FCM_SERVER_KEY = "<YOUR_FIREBASE_FCM_SERVER_KEY>"
# Google Service Account Private Key: Firebase Console->Cloud messaging->Manage Service Account->Firebase created account
GOOGLE_SRVACC_EMAIL = "<YOUR_GOOGLE_SERVICE_ACCOUNT_EMAIL>"
# Google Service Account Private Key: Firebase Console->Cloud messaging->Manage Service Account->Firebase created account->Keys->Add Key->Download JSON->private_key
GOOGLE_SRVACC_PRIVATE_KEY = "<YOUR_GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY>"
# Obtain in Google Cloud Console-><Project>->Credentials->Web client->Client ID
GOOGLE_CLIENT_ID = "<YOUR_GOOGLE_CLOUD_CLIENT_ID>"
# Obtain in Google Cloud Console-><Project>->Credentials->Web client->Client secret
GOOGLE_CLIENT_SECRET = "<YOUR_GOOGLE_CLOUD_CLIENT_SECRET>"
# Obtain in Flutter Firebase package. Which print on console when the App starts
TEST_DEVICE_TOKEN = "<YOUR_FCM_CLIENT_DEVICE_TOKEN>"
#### For Initial Database. Which is used in the Admin console.
INITIAL_ADMIN_EMAIL = "<YOUR_EMAIL_FOR_LOGIN>"
INITIAL_ADMIN_PASSWORD = "<YOUR_PASSWORD_FOR_LOGIN>"
INITIAL_TENANT_EMAIL = "<YOUR_FIRST_TENANT_LOGIN_EMAIL>"
INITIAL_TENANT_PASSWORD = "<YOUR_FIRST_TENANT_LOGIN_PASSWORD>"
##### AWS S3
S3_ACCESS_KEY = "<YOUR_S3_ACCESS_KEY>"
S3_ACCESS_SECRET = "<YOUR_S3_ACCESS_SECRET>"
S3_BUCKET = "<YOUR_S3_BUCKET>"
S3_REGION = "<YOUR_S3_REGION>"
S3_HOST = "<YOUR_S3_HOSTNAME>"
S3_ENDPOINT = "<YOUR_S3_ENDPOINT>"
##### Mailgun
MAILGUN_API_KEY = "<YOUR_MAILGUN_API_KEY>"
MAILGUN_API_URL = "<YOUR_MAILGUN_API_URL>"
TURNSTILE_SECRET = "<YOUR_MAILGUN_API_SECRET>"

[[env.staging.d1_databases]]
binding = "DB"
database_id = "<YOUR_D1_STAGING_DATABASE_ID>"

[env.production]

[env.production.vars]
USER_ENCRYPTION_KEY = "<512-bits encryption key>"
TENANT_ENCRYPTION_KEY = "<512-bits encryption key>"
API_SECRET = "<256-bits encryption key>"
DBINIT_SECRET = "<256-bits encryption key>"
SYSTEM_HOST = "http://localhost:3000" # CFW local server default port. (May change in future)
SYSTEM_EMAIL_SENDER = "<YOUR_EMAIL_SENDER_NAME_WITH_EMAIL>" # e.g. EstateMan <no_reply@propmanagement.com>
NOTIFICATION_ICON_URL = "https://f004.backblazeb2.com/file/vpms-hk/assets/logo3_b_120.png"
# Obtain in Firebase console->project settings->project ID
FIREBASE_PROJECT_ID = "<YOUR_FIREBASE_PROJECT_ID>"
# Obtain in Firebase console->project settings->cloud messaging->legacy API
FCM_SERVER_KEY = "<YOUR_FIREBASE_FCM_SERVER_KEY>"
# Google Service Account Private Key: Firebase Console->Cloud messaging->Manage Service Account->Firebase created account
GOOGLE_SRVACC_EMAIL = "<YOUR_GOOGLE_SERVICE_ACCOUNT_EMAIL>"
# Google Service Account Private Key: Firebase Console->Cloud messaging->Manage Service Account->Firebase created account->Keys->Add Key->Download JSON->private_key
GOOGLE_SRVACC_PRIVATE_KEY = "<YOUR_GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY>"
# Obtain in Google Cloud Console-><Project>->Credentials->Web client->Client ID
GOOGLE_CLIENT_ID = "<YOUR_GOOGLE_CLOUD_CLIENT_ID>"
# Obtain in Google Cloud Console-><Project>->Credentials->Web client->Client secret
GOOGLE_CLIENT_SECRET = "<YOUR_GOOGLE_CLOUD_CLIENT_SECRET>"
# Obtain in Flutter Firebase package. Which print on console when the App starts
TEST_DEVICE_TOKEN = "<YOUR_FCM_CLIENT_DEVICE_TOKEN>"
#### For Initial Database. Which is used in the Admin console.
INITIAL_ADMIN_EMAIL = "<YOUR_EMAIL_FOR_LOGIN>"
INITIAL_ADMIN_PASSWORD = "<YOUR_PASSWORD_FOR_LOGIN>"
INITIAL_TENANT_EMAIL = "<YOUR_FIRST_TENANT_LOGIN_EMAIL>"
INITIAL_TENANT_PASSWORD = "<YOUR_FIRST_TENANT_LOGIN_PASSWORD>"
##### AWS S3
S3_ACCESS_KEY = "<YOUR_S3_ACCESS_KEY>"
S3_ACCESS_SECRET = "<YOUR_S3_ACCESS_SECRET>"
S3_BUCKET = "<YOUR_S3_BUCKET>"
S3_REGION = "<YOUR_S3_REGION>"
S3_HOST = "<YOUR_S3_HOSTNAME>"
S3_ENDPOINT = "<YOUR_S3_ENDPOINT>"
##### Mailgun
MAILGUN_API_KEY = "<YOUR_MAILGUN_API_KEY>"
MAILGUN_API_URL = "<YOUR_MAILGUN_API_URL>"
TURNSTILE_SECRET = "<YOUR_MAILGUN_API_SECRET>"

[[env.production.d1_databases]]
binding = "DB"
database_id = "<YOUR_D1_PRODUCTION_DATABASE_ID>"

[site]
bucket = "./assets"

[build]
command = "node build.js"
