name = "estateman_cfw"
main="src/index.ts"
#main = "dist/index.mjs"
workers_dev = true
compatibility_date = "2022-02-03"
# kv_namespaces = [
# { binding = "BLOG_EXAMPLE", preview_id = "efca1d91ebb1480989cbaabb2a2f7d25", id = "1c06be2ff0274f8d8e90972f3d207cd3" }
# ]

[env.staging]

[[env.staging.d1_databases]]
binding = "DB"
database_id = "<YOUR_DATABASE_ID>"
preview_database_id = "<YOUR_DATABASE_ID>"

[site]
bucket = "./assets"

[build]
command = "node build.js"

[miniflare]
env_path=".dev.vars"