name = "estateman_cfw"
main="src/index.ts"
#main = "dist/index.mjs"
workers_dev = true
compatibility_date = "2022-02-03"
# kv_namespaces = [
# ]

[env.staging]

[[env.staging.d1_databases]]
binding = "DB"
database_id = "<YOUR_DATABASE_ID>"
preview_database_id = "<YOUR_DATABASE_ID>"

[site]
bucket = "./assets"

[build]
command = "node build.js"

[miniflare]
env_path=".dev.vars"